from datetime import datetime
from typing import Dict, List, Optional
import os


def export_report_txt(report_text: str, kpis: Dict, anomaly_result: Dict,
                       report_type: str = "Sales", save_dir: str = "reports") -> str:
    """Export report as a formatted text file."""
    os.makedirs(save_dir, exist_ok=True)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"{save_dir}/SmartReport_{report_type}_{timestamp}.txt"

    separator = "=" * 70
    thin_sep = "-" * 70

    content = f"""
{separator}
           SMARTREPORT AGENT — ENTERPRISE INTELLIGENCE REPORT
{separator}
Report Type  : {report_type} Intelligence Report
Generated At : {datetime.now().strftime('%B %d, %Y at %H:%M:%S')}
Agent Version: SmartReport v1.0 | Powered by Groq LLM + Statistical AI
{separator}

ANOMALY DASHBOARD
{thin_sep}
Total Anomalies   : {anomaly_result.get('total_anomalies', 0)}
High Severity     : {anomaly_result.get('high_severity', 0)}
Medium Severity   : {anomaly_result.get('medium_severity', 0)}

{thin_sep}
KEY PERFORMANCE INDICATORS
{thin_sep}
"""
    for key, val in kpis.items():
        label = key.replace('_', ' ').title()
        if isinstance(val, float):
            content += f"{label:<30}: {val:.2f}\n"
        elif isinstance(val, int):
            content += f"{label:<30}: {val:,}\n"
        else:
            content += f"{label:<30}: {val}\n"

    content += f"""
{thin_sep}
ANOMALIES DETECTED
{thin_sep}
"""
    if anomaly_result.get('anomalies'):
        for i, a in enumerate(anomaly_result['anomalies'], 1):
            content += f"""
[{i}] Severity  : {a['severity']}
    Type      : {a['type']}
    Date      : {a['date']}
    Detail    : {a['detail']}
"""
    else:
        content += "No anomalies detected in this period.\n"

    content += f"""
{thin_sep}
AI-GENERATED NARRATIVE REPORT
{thin_sep}

{report_text}

{separator}
END OF REPORT
Generated by SmartReport Agent | Enterprise AI Platform
{separator}
"""

    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)

    return filename


def export_report_html(report_text: str, kpis: Dict, anomaly_result: Dict,
                        report_type: str = "Sales", save_dir: str = "reports") -> str:
    """Export report as styled HTML file."""
    os.makedirs(save_dir, exist_ok=True)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"{save_dir}/SmartReport_{report_type}_{timestamp}.html"

    kpi_rows = ""
    for key, val in kpis.items():
        label = key.replace('_', ' ').title()
        if isinstance(val, float):
            formatted = f"{val:.2f}"
        elif isinstance(val, int):
            formatted = f"{val:,}"
        else:
            formatted = str(val)
        kpi_rows += f'<tr><td class="label">{label}</td><td class="value">{formatted}</td></tr>'

    anomaly_rows = ""
    for a in anomaly_result.get('anomalies', []):
        sev_class = "high" if a['severity'] == 'HIGH' else "medium"
        anomaly_rows += f"""
        <tr>
            <td><span class="badge {sev_class}">{a['severity']}</span></td>
            <td>{a['type']}</td>
            <td>{a['date']}</td>
            <td>{a['detail']}</td>
        </tr>"""

    report_html = report_text.replace('\n## ', '\n<h2>').replace('\n### ', '\n<h3>')
    report_html = report_html.replace('\n- ', '\n<li>').replace('\n**', '\n<strong>').replace('**\n', '</strong>\n')

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>SmartReport Agent — {report_type} Report</title>
<style>
  body {{ font-family: 'Georgia', serif; background: #f4f6f9; color: #2c3e50; margin: 0; padding: 20px; }}
  .container {{ max-width: 900px; margin: auto; background: white; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); overflow: hidden; }}
  .header {{ background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); color: white; padding: 30px 40px; }}
  .header h1 {{ margin: 0; font-size: 26px; letter-spacing: 1px; }}
  .header p {{ margin: 5px 0 0; opacity: 0.7; font-size: 13px; }}
  .section {{ padding: 24px 40px; border-bottom: 1px solid #eee; }}
  .section h2 {{ font-size: 16px; color: #1a1a2e; text-transform: uppercase; letter-spacing: 1px; border-left: 4px solid #e74c3c; padding-left: 12px; }}
  .kpi-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }}
  .kpi-card {{ background: #f8f9fa; border-radius: 8px; padding: 14px; border-left: 3px solid #3498db; }}
  .kpi-card .label {{ font-size: 11px; color: #888; text-transform: uppercase; }}
  .kpi-card .value {{ font-size: 20px; font-weight: bold; color: #1a1a2e; margin-top: 4px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th {{ background: #1a1a2e; color: white; padding: 10px 12px; text-align: left; font-size: 11px; text-transform: uppercase; }}
  td {{ padding: 10px 12px; border-bottom: 1px solid #eee; }}
  tr:hover {{ background: #f8f9fa; }}
  .badge {{ padding: 3px 8px; border-radius: 4px; font-size: 10px; font-weight: bold; }}
  .badge.high {{ background: #ffeaea; color: #e74c3c; }}
  .badge.medium {{ background: #fff3cd; color: #f39c12; }}
  .narrative {{ line-height: 1.8; font-size: 14px; white-space: pre-line; }}
  .footer {{ background: #f8f9fa; padding: 16px 40px; text-align: center; font-size: 11px; color: #aaa; }}
  .stats-bar {{ display: flex; gap: 20px; padding: 20px 40px; background: #1a1a2e10; }}
  .stat {{ text-align: center; flex: 1; }}
  .stat .num {{ font-size: 28px; font-weight: bold; color: #e74c3c; }}
  .stat .lbl {{ font-size: 11px; color: #666; text-transform: uppercase; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>📊 SmartReport Agent</h1>
    <p>{report_type} Intelligence Report &nbsp;|&nbsp; Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}</p>
  </div>
  <div class="stats-bar">
    <div class="stat"><div class="num">{anomaly_result.get('total_anomalies', 0)}</div><div class="lbl">Total Anomalies</div></div>
    <div class="stat"><div class="num" style="color:#e74c3c">{anomaly_result.get('high_severity', 0)}</div><div class="lbl">High Severity</div></div>
    <div class="stat"><div class="num" style="color:#f39c12">{anomaly_result.get('medium_severity', 0)}</div><div class="lbl">Medium Severity</div></div>
    <div class="stat"><div class="num" style="color:#27ae60">{len(kpis)}</div><div class="lbl">KPIs Tracked</div></div>
  </div>
  <div class="section">
    <h2>Key Performance Indicators</h2>
    <div class="kpi-grid">
      {_kpi_cards(kpis)}
    </div>
  </div>
  <div class="section">
    <h2>Anomalies Detected</h2>
    {"<p style='color:#27ae60'>✅ No anomalies detected in this period.</p>" if not anomaly_result.get('anomalies') else f'''
    <table>
      <tr><th>Severity</th><th>Type</th><th>Date</th><th>Detail</th></tr>
      {anomaly_rows}
    </table>'''}
  </div>
  <div class="section">
    <h2>AI Analysis Narrative</h2>
    <div class="narrative">{report_text}</div>
  </div>
  <div class="footer">SmartReport Agent · Enterprise AI Platform · {datetime.now().year}</div>
</div>
</body></html>"""

    with open(filename, 'w', encoding='utf-8') as f:
        f.write(html)
    return filename


def _kpi_cards(kpis: Dict) -> str:
    cards = ""
    for key, val in kpis.items():
        label = key.replace('_', ' ').title()
        if isinstance(val, float):
            formatted = f"{val:.2f}"
            if 'rate' in key or 'margin' in key or 'achievement' in key:
                formatted += "%"
        elif isinstance(val, int):
            formatted = f"{val:,}"
        else:
            formatted = str(val)
        cards += f'<div class="kpi-card"><div class="label">{label}</div><div class="value">{formatted}</div></div>'
    return cards
