import os
import json
import numpy as np
import requests
from datetime import datetime
from typing import Dict, List, Optional

try:
    from config import GROQ_MODEL
except ImportError:
    GROQ_MODEL = "llama-3.1-8b-instant"

GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"


def _make_serializable(obj):
    """Recursively convert numpy/pandas types to native Python for JSON serialization."""
    if isinstance(obj, dict):
        return {k: _make_serializable(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [_make_serializable(i) for i in obj]
    elif isinstance(obj, np.integer):
        return int(obj)
    elif isinstance(obj, np.floating):
        return round(float(obj), 2)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    else:
        return obj


def call_groq(prompt: str, api_key: str, model: str = GROQ_MODEL, temperature: float = 0.3) -> str:
    """Call Groq API and return response text."""
    if not api_key or api_key == "gsk_your_groq_api_key_here":
        return _fallback_report(prompt)

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": model,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are SmartReport AI, an enterprise business intelligence agent. "
                    "You generate concise, professional executive-level business reports. "
                    "Use clear language, highlight risks boldly, and always end with 3 actionable recommendations. "
                    "Format responses in clean sections with headers. Be data-driven and specific."
                )
            },
            {"role": "user", "content": prompt}
        ],
        "temperature": temperature,
        "max_tokens": 1200
    }
    try:
        response = requests.post(GROQ_API_URL, headers=headers, json=payload, timeout=30)
        response.raise_for_status()
        return response.json()["choices"][0]["message"]["content"]
    except requests.exceptions.ConnectionError:
        return _fallback_report(prompt)
    except requests.exceptions.HTTPError as e:
        status_code = e.response.status_code if e.response is not None else "unknown"
        print(f"Groq API HTTP error ({status_code}) using model '{model}': {e}")
        return _fallback_report(prompt)
    except (KeyError, IndexError, ValueError) as e:
        print(f"Unexpected Groq API response shape: {e}")
        return _fallback_report(prompt)
    except requests.exceptions.RequestException as e:
        print(f"Groq API request failed: {e}")
        return _fallback_report(prompt)


def _fallback_report(prompt: str) -> str:
    """Fallback report when API is unavailable."""
    return """## Executive Summary

**SmartReport AI - Automated Analysis Report**

*Note: Running in offline mode (LLM unavailable). Showing rule-based analysis.*

### Key Findings
- Anomaly detection completed using statistical methods (Z-score + IQR)
- All metrics have been analyzed against historical baselines
- Threshold breach monitoring active across all KPIs

### Performance Overview
The data has been processed and anomalies flagged based on statistical deviation analysis. Please review the anomaly table below for specific incidents requiring attention.

### Risk Assessment
- HIGH severity anomalies require immediate action
- MEDIUM severity anomalies should be reviewed within 24 hours
- Trend analysis indicates period-over-period variance

### Recommendations
1. **Immediate**: Investigate all HIGH severity anomalies flagged in the report
2. **Short-term**: Review operational thresholds and calibrate if needed
3. **Strategic**: Implement automated alerting for real-time monitoring

---
*Report generated by SmartReport Agent | Rule-based mode*"""


def generate_sales_report(kpis: Dict, anomaly_result: Dict, api_key: str, date_range: str = "") -> str:
    """Generate LLM-powered sales intelligence report."""
    anomaly_summary = "\n".join([
        f"- [{a['severity']}] {a['type']} on {a['date']}: {a['detail']}"
        for a in anomaly_result['anomalies'][:8]
    ])
    insights_text = "\n".join([f"- {i}" for i in anomaly_result['insights']])

    prompt = f"""Generate a professional enterprise sales intelligence report for the following data:

**Period:** {date_range or 'Current Period'}

**KPI Summary:**
- Total Revenue: Rs.{kpis.get('total_revenue', 0):,.0f}
- Average Daily Revenue: Rs.{kpis.get('avg_daily_revenue', 0):,.0f}
- Total Units Sold: {kpis.get('total_units', 0):,}
- Average Order Value: Rs.{kpis.get('avg_order_value', 0):,.2f}
- Target Achievement: {kpis.get('target_achievement', 0):.1f}%
- Return Rate: {kpis.get('return_rate', 0):.2f}%
- Gross Margin: {kpis.get('gross_margin', 0):.1f}%

**Anomalies Detected ({anomaly_result['total_anomalies']} total - {anomaly_result['high_severity']} HIGH, {anomaly_result['medium_severity']} MEDIUM):**
{anomaly_summary if anomaly_summary else 'No anomalies detected.'}

**Data Insights:**
{insights_text}

Write a structured executive report with: Executive Summary, Performance Analysis, Anomaly Assessment, Risk Flags, and 3 Actionable Recommendations. Be specific with numbers."""

    return call_groq(prompt, api_key)


def generate_operations_report(kpis: Dict, anomaly_result: Dict, api_key: str) -> str:
    """Generate LLM-powered operations report."""
    anomaly_summary = "\n".join([
        f"- [{a['severity']}] {a['type']} on {a['date']}: {a['detail']}"
        for a in anomaly_result['anomalies'][:8]
    ])
    insights_text = "\n".join([f"- {i}" for i in anomaly_result['insights']])

    prompt = f"""Generate a professional enterprise operations performance report:

**KPI Summary:**
- Total Checks Performed: {kpis.get('total_checks', 0)}
- Anomalies Detected: {kpis.get('anomaly_count', 0)}
- Compliance Rate: {kpis.get('compliance_rate', 0):.1f}%

**Anomalies ({anomaly_result['total_anomalies']} total):**
{anomaly_summary if anomaly_summary else 'No anomalies detected.'}

**Department Insights:**
{insights_text}

Write a structured operations report with: Executive Summary, Department Performance, Critical Issues, Risk Assessment, and 3 Recommendations."""

    return call_groq(prompt, api_key)


def generate_forecast_narrative(df_summary: Dict, api_key: str) -> str:
    """BONUS FEATURE: Generate AI forecast narrative."""
    safe_summary = _make_serializable(df_summary)
    prompt = f"""Based on this business data summary, generate a brief 7-day forward-looking forecast:

{json.dumps(safe_summary, indent=2)}

Provide:
1. Revenue forecast trend (up/down/stable) with reasoning
2. Key risk factors to watch
3. Opportunities to capitalize on
4. One specific metric to monitor daily

Keep it to 200 words, executive-level, actionable."""

    return call_groq(prompt, api_key, temperature=0.5)


def generate_email_summary(report_text: str, anomaly_count: int, high_severity: int, api_key: str) -> str:
    """Generate a short email-ready summary."""
    prompt = f"""Convert this report into a crisp email alert (max 150 words) for a business executive.

Report excerpt:
{report_text[:800]}

Stats: {anomaly_count} anomalies detected, {high_severity} HIGH severity.

Format as: Subject line, then body. Professional, urgent if high severity > 0."""

    return call_groq(prompt, api_key, temperature=0.2)
